### ISSUE TITLE
Feature Request: allow _ and = char toggle +/- 0.5 seconds interval change 

### ISSUE THREAD

**Issue by terryding77** [blacknon/hwatch#100]
for laptop compute, there is no seperated - and + key on keyboard, so that minus "-" and plus "+" are the key near the backspace.
**+**  equals **shift =**
**_**  equals **shift -**
so can we ignore the shift command to allow _ and = char to change the interval?

**Comment by blacknon** [comment]
Looks good!

**Comment by blacknon** [comment]
In order to handle this issue in a more general manner, we have created a new issue #106 and have responded to it.
You can set a custom keymap with the `-K` option.

can set `=` with `equal`.

**Comment by blacknon** [comment]
I think it's okay now, so I'll close it.
