### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by dudul** [blacknon/hwatch#115]
Any chance for windows build?

**Comment by blacknon** [comment]
I just realized that the Windows binaries are missing.
I was using ncurses at first, so maybe that's why.

will add the job at the next and subsequent version builds.

**Comment by blacknon** [comment]
I added it to the BUILD JOB.
I have also done a quick check, but if there are any details that bother you, I would appreciate it if you could raise another Issue.

**Comment by blacknon** [comment]
I think it will probably be okay, so I'll close it.
