### ISSUE TITLE
FR: Set a maximum for number of history entries remembered

### ISSUE THREAD

**Issue by ilyagr** [blacknon/hwatch#118]
I opened my task manager and was surprised to discover that `hwatch` was unexpectedly using 8GB of memory. This was because one of the processes I was `hwatch`-ing was updating much more often than I thought (it showed minutes or seconds since last operation).

I'd like `hwatch` to be pre-configured to remember a maximum of, say, 5000 different past outputs for a command. There could also be an option to change this maximum.

**Comment by blacknon** [comment]
Indeed, execution history information is stored in memory, memory usage increases in proportion to the history information.

Yes, it seems that it would be better to have a fixed upper limit by default.
I would like to allow this upper limit to be optionally specified, and in some cases to be specified as unlimited.

Apart from this, it would be a good idea to check unnecessary memory usage as well.
This, I will create another issue .

**Comment by blacknon** [comment]
I added the limit option (`-L, --limit`) in version 0.3.14.
default value is 5000, set 0 is unlimited.

I think it will probably work fine, so please check it and close the Issue if it looks ok.
Thank you for the Issue.

**Comment by ilyagr** [comment]
That seems like it should be fine, thank you very much! I'll just close the issue now, and I'll reopen it (or file a new one) if I have any problems.
