### ISSUE TITLE
The `s` binding is a bit confusing when border is disabled or the text is too short

### ISSUE THREAD

**Issue by ilyagr** [blacknon/hwatch#128]
The `s` binding does nothing when the border is disabled or if the window fits on one screen, which is a bit confusing.

Perhaps `b` could be a tri-state toggle: no border, border without scrollbar, border with scrollbar?

When the scrollbar is on, the whole "border" could be drawn thick as though it was a huge scrollbar (just to make it less confusing that these are two different states).

**Comment by blacknon** [comment]
Come to think of it, maybe you are right.
Since I had created the METHOD separately, I had implemented the key bindings separately for the time being.

In the next version at 0.3.15, change the default behavior to a toggle that enables/disables the border and scrollbars as a set.
