### ISSUE TITLE
For long output, the scrollbar appears and disappears as the text scrolls

### ISSUE THREAD

**Issue by ilyagr** [blacknon/hwatch#132]
This applies to either hwatch 0.3.14 or the prerelease (same setup as https://github.com/blacknon/hwatch/issues/129#issuecomment-2164092903)

If I run `HWATCH= cargo +beta run -- "seq 1000"` (or `hwatch "seq 1000"`) and turn on both border and scrollbar, and start scrolling down, the scrollbar appears and disappears depending on how far down I scroll. Some screenshots follow.

No scrollbar at 31 (I did not turn it off):
![image](https://github.com/blacknon/hwatch/assets/4123047/f1d96d62-ef94-4f62-9dfa-07bed0e124c3)

Scrollbar appears at 52:
![image](https://github.com/blacknon/hwatch/assets/4123047/fc909685-97d9-4904-aa21-7eac2b8ce580)

There's no scrollbar at the top (1), not pictured

There is a scroll bar shown at 4 (the exact number might depend on the number of terminal rows), not pictured.

--------

You can also get a good demo by finding a number where the scrollbar shows and resizing the terminal.

**Comment by blacknon** [comment]
Hmm...
This event did not reproduce in my environment...

**Comment by ilyagr** [comment]
I can reproduce this with 0.3.14 but not with 0.3.15. I'm guessing you fixed it without realizing it. :)

**Comment by blacknon** [comment]
I see 🙏
