### ISSUE TITLE
"Error: Initial console modes not set" on Windows

### ISSUE THREAD

**Issue by UnderCooled** [blacknon/hwatch#136]
Crossterm issue: https://github.com/crossterm-rs/crossterm/issues/660

Possible fix: https://github.com/fujiapple852/trippy/pull/117/files

**Comment by cdituri** [comment]
@UnderCooled Thanks for report and links 👍 I took a pass at fixing this issue because `hwatch` is awesome and Windows needs its awesomeness 😄 

#143 provides a fix. Works on my end but if you have any spare cycles to try it out and report back all the better.

**Comment by UnderCooled** [comment]
> @UnderCooled Thanks for the report and links 👍 I took a pass at fixing this issue because `hwatch` is awesome and Windows needs its awesomeness 😄
> 
> #143 provides a fix. Works on my end but if you have any spare cycles to try it out and report back all the better.

Works great, thanks! 👍

**Comment by blacknon** [comment]
Thanks!
