### ISSUE TITLE
Installation via `cargo install hwatch`

### ISSUE THREAD

**Issue by trustin** [blacknon/hwatch#14]
It'd be nice if I can install the `hwatch` command by running `cargo install hwatch`. I install tools like the following in this way already, so it'd be great if I can do that same for `hwatch`.

- `bat`
- `exa`
- `fd-find`
- `procs`
- `ripgrep`
- `svgbob_cli`

**Comment by blacknon** [comment]
thank you very much.
I tried to correspond.

**Comment by trustin** [comment]
Thanks a lot. I confirmed I can install it with `cargo install hwatch`. 🙇
