### ISSUE TITLE
Bug: when changing size of a terminal in tmux, hwatch crashes system

### ISSUE THREAD

**Issue by gkielian** [blacknon/hwatch#43]
First of all, wanted to say thanks for creating this!  This has been a great help to my workflow.

I've noticed a few of my machines have crashed when I resize the pane that I run hwatch in, even for simple tasks, wanted to relay the steps:

Steps to reproduce:

1. create a split pane with tmux and run `hwatch ls`
2. enable diff mode
3. resize the pane

Sharing an image of the cpu usage spiking afterwards from htop (other hwatch processes are sub 100%):

![image](https://user-images.githubusercontent.com/10952473/155082572-af4b7520-09f0-4fec-b5a0-601df4b71e12.png)

I've tried this on a few machines both debian based, one of these is Ubuntu 20.04.

Thanks again, and let me know if there's any further info that could help find the bug.

**Comment by blacknon** [comment]
Thank you for using,and for telling me!

The behavior will be reproduced and will be fixed in the next version.
