### ISSUE TITLE
When running hwatch in tmux split + Kitty 0.25.0, moving mouse wil resize the pane

### ISSUE THREAD

**Issue by budimanjojo** [blacknon/hwatch#51]
It's a strange bug, but it's weird that it's only happening in one of my machine.
When I'm in tmux split, then running `hwatch command`, moving my mouse will resize the tmux window (sometimes it just go into tmux selection move). I thought this is related to https://github.com/blacknon/hwatch/issues/43 but I tried version 0.3.3 and it's still happening.
Here is the screenrecord.

https://user-images.githubusercontent.com/13085918/169562136-256cdb31-614f-4978-ad53-65709e194d46.mp4

As soon as I run `hwatch` and then move my mouse, it will resize the pane following my mouse movement, And it will stop if I close hwatch.

**Comment by budimanjojo** [comment]
I found something new, it's only happening if my terminal is `kitty` version `0.25.0`. I'll update the title.

**Comment by budimanjojo** [comment]
Can u reproduce it? I got similar result on both Ubuntu 22.04 and Arch Linux. With latest kitty and tmux

**Comment by blacknon** [comment]
Well, I haven't confirmed it yet...

**Comment by budimanjojo** [comment]
I'll close this now as it should be a kitty bug

**Comment by ilyagr** [comment]
This seems to be fixed in Kitty 0.25.1.

**Comment by budimanjojo** [comment]
@ilyagr Thanks! Good to know although I'm now using alacritty because of this
