### ISSUE TITLE
[Feature Request] Allow pass commands to exec like `watch -x`.

### ISSUE THREAD

**Issue by VergeDX** [blacknon/hwatch#52]
Original `watch` command allow us "pass command to exec instead of "sh -c"":
https://gitlab.com/procps-ng/procps/-/blob/v3.3.16/watch.c#L100

But there is no equivalent in `hwatch`:
https://github.com/blacknon/hwatch/blob/0.3.4/src/exec.rs#L50=

Previous: `hwatch 'nu -c "jc mpstat | from json"'`,
After this feature: `hwatch -x nu -c "jc mpstat | from json"`.

Which saves a single quote wrap, to gain better colors of terminal:
![image](https://user-images.githubusercontent.com/25173827/169962372-60e65931-4a84-4e66-b5f2-a0635f532345.png)

**Comment by VergeDX** [comment]
I can make a PR or patches, if you think this is acceptable.  
Thanks for this useful CLI tools again!

**Comment by blacknon** [comment]
Thank you for this Issue!
It was a feature I was thinking of adding someday, but I was putting it off.

I would like to add it in version 0.3.5 or 0.3.6.

**Comment by VergeDX** [comment]
Yes I saw your comments in source code, good luck!
