### ISSUE TITLE
`hwatch wc -l log.log` consumes the `-l` option that was meant for `wc` not `hwatch`

### ISSUE THREAD

**Issue by jtara1** [blacknon/hwatch#55]

**Comment by jtara1** [comment]
Workaround solution:

```
hwatch wc log.log -- -l
```

**Comment by blacknon** [comment]
NOTE:

As a response to this issue, `trailing_var_arg (true)` was added to the processing of the corresponding `clap::Command::new()`.

https://github.com/blacknon/hwatch/blob/969cb93b9273d64ff8e5f7b85a790a47df471801/src/main.rs#L107-L113
