### ISSUE TITLE
Watching a command with pipe

### ISSUE THREAD

**Issue by trustin** [blacknon/hwatch#56]
Hi!

I'm trying to use `hwatch` for the following command:

```
ls | wc -l
```

I tried the following but none worked so far:

- `hwatch -- 'ls | wc -l'`
- `hwatch -- ls '|' wc -l`

**Comment by blacknon** [comment]
Wow!

I also confirmed it.
Apparently, it seems to be a bug caused by the change in Version 0.3.5.

**Comment by blacknon** [comment]
The cause is that the processing at the time of command execution was changed in order to specify the -s option.

https://github.com/blacknon/hwatch/blob/4a942587f5d60e477d6c7ae40c653b87d7e23b20/src/exec.rs#L58-L90

We will fix it early.

**Comment by blacknon** [comment]
NOTE:

The cause was that it was quoted by using `shell_words :: join`.

https://github.com/blacknon/hwatch/blob/4a942587f5d60e477d6c7ae40c653b87d7e23b20/src/exec.rs#L54

**Comment by trustin** [comment]
Thanks a lot for a very quick fix, @blacknon! 🙇
