### ISSUE TITLE
Long files confuse `hwatch`

### ISSUE THREAD

**Issue by ilyagr** [blacknon/hwatch#87]
To reproduce: with `hwatch 0.3.9` on Linux: 

1. Download [qq.tar.gz](https://github.com/blacknon/hwatch/files/10575559/qq.tar.gz) and unpack it. **Update:** I reuploaded the file, the previous one had an insane path inside the tar file

2. Run `hwatch cat qq` or `HWATCH= hwatch cat qq`

On my machine, this causes `hwatch` freeze and no part of the file is ever printed. The file has color sequences in it; `hwatch --color cat qq` also freezes. `less -R qq` and `watch --color cat qq` work with no problems.

For illustration, here's the end of the file in `less -R`:
![image](https://user-images.githubusercontent.com/4123047/216499592-4a05b625-053a-4c51-b642-fac9038de41e.png)

The file is obtained with [`jj log`](https://github.com/martinvonz/jj) which is equivalent to `git log`. I usually use `hwatch` with `jj log` with no problems, but for this particular state of the repo something went wrong.

I may or may not try to investigate this myself in the near future.

**Comment by ilyagr** [comment]
I think I figured out the cause. The file is simply too long.  

```bash
$ hwatch "cat qq|head -n 500"   # Works
$ hwatch "cat qq|head -n 700"   # Does not work
```

I think this should still be tracked as a bug. `hwatch` should handle large file, at least by failing gracefully or cutting them off when a file is too long.

**Comment by blacknon** [comment]
Thanks!

> I think this should still be tracked as a bug. hwatch should handle large file, at least by failing gracefully or cutting them off when a file is too long.

That's certainly true.
I'll try to figure out how to fix it.

**Comment by blacknon** [comment]
It certainly doesn't move...
In version 0.3.11, I tried to cat the output of `git log --color=always` and `git log` (3000 lines), but it doesn't seem to be working.

**Comment by blacknon** [comment]
I think this process is probably the cause.

https://github.com/blacknon/hwatch/blob/master/src/exec.rs#L99-L115

**Comment by blacknon** [comment]
Closed because it was applied in version 0.3.12.
Thank you for issue!

**Comment by ilyagr** [comment]
It works beautifully now. No more `| head -n 300` for every command. Thank you!

**Comment by fedorkanin** [comment]
I use `hwatch` to display live git graph in terminal. In small repos it works fine, but in medium-size and larger repos it is impossible to use, the scroll is extremely slow and laggy. This a command example:

```bash
hwatch -n 100 -c --no-title --differences=none -- 'git log --all --oneline --graph --decorate --color | head -n 10000'
```

Note, that even with 10,000 lines and 100s refresh interval it is extremely slow. 10,000 lines doesn't seem like a lot to me, maybe there is some kind of solution?
