### ISSUE TITLE
small glitch

### ISSUE THREAD

**Issue by leapfog** [blacknon/hwatch#88]
When in diff-mode, toggling the title line isn't perfect: a single character isn't cleared.
I can trigger it with any of these commands (i.e. run them and than press `t`).

$ `hwatch -d date +%R`
$ `hwatch -d echo test`
$ `hwatch -d echo {0..9}`
$ `hwatch -d echo {a..z} {A..Z}`

The last one needs a small enough terminal width, for example 80 chars.

**Comment by leapfog** [comment]
There is another (similar?) issue when running `hwatch date +%T` and press `2` (for Line-Diff) and `1` (for Watch-Diff).

**Comment by leapfog** [comment]
as far as I can tell, zaidhaan's PR fixes all observed issues

**Comment by blacknon** [comment]
Sorry for the late confirmation.
I will respond in early April.

**Comment by blacknon** [comment]
Marge in version 0.3.10. Close.
