### ISSUE TITLE
switch library to ratatui

### ISSUE THREAD

**Issue by blacknon** [blacknon/hwatch#91]
The library ([tui-rs](https://github.com/fdehau/tui-rs/issues/654)) we were using is no longer under development, so we switch to [ratatui](https://github.com/tui-rs-revival/ratatui), which we forked.

**Comment by blacknon** [comment]
For some reason, as soon as I switched to ratatui, watch/history disappeared...

https://github.com/blacknon/hwatch/commit/b6e4be7463a7c6a41d3848ce3f5da29942125648

**Comment by blacknon** [comment]
> For some reason, as soon as I switched to ratatui, watch/history disappeared...
> 
> [b6e4be7](https://github.com/blacknon/hwatch/commit/b6e4be7463a7c6a41d3848ce3f5da29942125648)

The following areas are likely to be the cause of the problem.

https://github.com/blacknon/hwatch/blob/b6e4be7463a7c6a41d3848ce3f5da29942125648/src/app.rs#L288-L305

**Comment by orhun** [comment]
Hey, maintainer of `ratatui` here. Can you point out to me the code/change that broke `Constraint::Max` for you? I would like to understand what happened there and possibly add a note to the changelog.

**Comment by blacknon** [comment]
Sorry, it was a long time ago and my memory has faded.
I will look into it and if I find out, I will describe it. 🙇
