### ISSUE TITLE
Got panic

### ISSUE THREAD

**Issue by nkh** [blacknon/hwatch#97]
![screenshot_2023-07-25_18-29-04](https://github.com/blacknon/hwatch/assets/45409/64c11acf-c2f1-4a16-b90d-d3bf6991030e)

crashed multiple time but of course not when I was trying to get it to crash so I only got a screenshot.

I'm running this command: hwatch -n 0.05 -d -N -t shuf -i1-10 -n5

I press d, to get a diff

sometimes it crashes on itself other when quitting

**Comment by injust** [comment]
Just ran into this as well. Happened when I was pressing 0/1/2/3 to switch between diff modes.

**Comment by blacknon** [comment]
Thank you for information.
I will check on my end.

**Comment by blacknon** [comment]
It's probably fixed.
Thank you for raising the issue!
