### ISSUE TITLE
Reverse lines in output of watched command

### ISSUE THREAD

**Issue by sanmai-NL** [blacknon/hwatch#99]
Some popular command statements users use `hwatch` with, [for example Kubernetes `kubectl`](https://stackoverflow.com/questions/57294739/kubernetes-display-pods-by-age-in-ascending-order), depend on extra tools and a pipeline to reverse their output. As far as I know, using a pipeline with `hwatch` requires verbose and suboptimal work-arounds, such as invoking `hwatch sh -c '...'`. Can `hwatch` instead support to reverse its output in terms of lines?

**Comment by blacknon** [comment]
Do you mean an option to reverse the order without intervening the `tac` command? 🤔 

I'll think about it a little.

**Comment by blacknon** [comment]
Added a new `reverse` mode.
You can switch using the `-r` option or the `r` key.

Since we have finished adding the functionality, we will close this issue.
Thank you for the issue.
